name: SonarQube
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze (SonarCloud)
    runs-on: ubuntu-latest

    steps:
      - name: 🧩 Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Importante para que SonarCloud analice correctamente el historial de commits

      - name: ☕ Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'
          cache: maven

      - name: 💾 Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: 💽 Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: 🛠️ Build and analyze (Backend)
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          # Entrar a la carpeta Backend solo si existe
          if [ -d "Backend" ]; then cd Backend; fi

          # Limpia y compila sin ejecutar tests
          mvn -B clean package \
            -DskipTests=true \
            -Dmaven.test.skip=true \
            -Dspring.test.context.enabled=false \
            org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=1Zamuken1_taller_calidad_software_Salsamentaria \
            -Dsonar.organization=1zamuken1 \
            -Dsonar.host.url=https://sonarcloud.io
